const state = {
  categoryTags: [{
    tag: '经典',
    url: 'https://m.douban.com/movie/classic',
    id: 0
  }, {
    tag: '冷门佳片',
    url: 'https://m.douban.com/movie/underrated',
    id: 1
  }, {
    tag: '豆瓣高分',
    url: 'https://m.douban.com/movie/doubantop',
    id: 2
  }, {
    tag: '动作',
    url: 'https://m.douban.com/movie/action',
    id: 3
  }, {
    tag: '喜剧',
    url: 'https://m.douban.com/movie/comedy',
    id: 4
  }, {
    tag: '爱情',
    url: 'https://m.douban.com/movie/love',
    id: 5
  }, {
    tag: '悬疑',
    url: 'https://m.douban.com/movie/mystery',
    id: 6
  }, {
    tag: '恐怖',
    url: 'https://m.douban.com/movie/horror',
    id: 7
  }, {
    tag: '科幻',
    url: 'https://m.douban.com/movie/scifi',
    id: 8
  }, {
    tag: '治愈',
    url: 'https://m.douban.com/movie/sweet',
    id: 9
  }, {
    tag: '文艺',
    url: 'https://m.douban.com/movie/artfilm',
    id: 10
  }, {
    tag: '成长',
    url: 'https://m.douban.com/movie/youth',
    id: 11
  }, {
    tag: '动画',
    url: 'https://m.douban.com/movie/animation',
    id: 12
  }, {
    tag: '华语',
    url: 'https://m.douban.com/movie/chinese',
    id: 13
  }, {
    tag: '欧美',
    url: 'https://m.douban.com/movie/western',
    id: 14
  }, {
    tag: '韩国',
    url: 'https://m.douban.com/movie/korean',
    id: 15
  }, {
    tag: '日本',
    url: 'https://m.douban.com/movie/japanese',
    id: 16
  }, ]
}

export default({
  state
})